version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254

services:

  weblogic-admin: 
    build: 
      context: image/weblogic-admin
    hostname: weblogic.admin.com
    volumes:
      - /Users/wuguanlong/Desktop:/home/user/Desktop
    networks:
      vpcbr:
        ipv4_address: 172.28.1.5
    ports:
      - "7001:7001"

  
