version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254

services:

  build-env:
    container_name: build-env
    build:
      context: image/dev-env
    volumes:
      - /Users/wuguanlong/Desktop:/home/user/Desktop
    environment:
      - PATH=/usr/local/gradle-5.0/bin:/usr/local/zulu8.66.0.15-ca-jdk8.0.352-linux_x64/bin:$PATH
      - GRADLE_HOME=/usr/local/gradle-5.0
      - JAVA_HOME=/usr/local/zulu8.66.0.15-ca-jdk8.0.352-linux_x64
      - REPO_PATH=/home/user/Desktop
    networks:
      vpcbr:
        ipv4_address: 172.28.1.3

  weblogic-admin: 
    container_name: weblogic-admin
    build: 
      args:
        SERVER_NAME: Server-0
      context: image/weblogic-admin
    hostname: weblogic.admin.com
    environment:
      - SERVICE_NAME=Server-0
    volumes:
      - /Users/wuguanlong/Desktop:/home/user/Desktop
    networks:
      vpcbr:
        ipv4_address: 172.28.1.5
    ports:
      - "7001:7001"
      - "7878:7878" # EJB Port - Proxied Port should be the same as Server port
  
  weblogic-slave1: 
    container_name: weblogic-slave1
    build: 
      args: 
        SERVER_NAME: Server-1
      context: image/weblogic-admin
    hostname: weblogic.slave1.com
    environment:
      - SERVICE_NAME=Server-1
    volumes:
      - /Users/wuguanlong/Desktop:/home/user/Desktop
    networks:
      vpcbr:
        ipv4_address: 172.28.1.6
    ports:
      - "7772:7772" # EJB Port- Proxied Port should be the same as Server port
    command: /usr/sbin/init

  
